### PR TITLE
fix: Add cleanup in useEffecct & store latitude and longitude in localStorage

### LINKED ISSUE #30: fix: Save user location in memory
Right now whenever we navigate to the Home page, it is asking for location. What we can do is to save the location in browser memory for some specific amount of time (let's say 15 minutes), and within that time we can use that location for querying the backend server. This will improve the user experience as the current implementation will annoy the user as he/she has to continuously enter the location.

### PR DESCRIPTION
**Pull request by ashrafmahmood**
fix #30

### CODE REVIEW

**Comment by Haider8** [comment]
Not taking the location from storage when I reload. Please check

**Comment by Haider8** [comment]
@ashrafmahmood Finalize this PR

**Comment by ashrafmahmood** [comment]
@Haider8  Please check this

File: src/components/Home/Home.js [hunk 1]
```diff
@@ -17,49 +20,98 @@ function Home () {
   useEffect(() => {
     async function position () {
       try {
-        await navigator.geolocation.getCurrentPosition(function (position) {
-          setLatitude(position.coords.latitude)
-          setLongitude(position.coords.longitude)
-        })
+        const now = new Date()
+        if (JSON.parse(localStorage.getItem('location') === null) || now.getTime() > JSON.parse(localStorage.getItem('location')).expiryTime) {
```
Comment (Haider8) [inline src/components/Home/Home.js]: At so many places, we are doing `JSON.parse(localStorage.getItem('location')`. Can we also make a separate module for this? Let's say `utils/storage` in this case

File: src/components/Home/Home.js [hunk 2]
```diff
@@ -17,49 +20,98 @@ function Home () {
...
+          await navigator.geolocation.getCurrentPosition((pos) => {
+            if (pos.coords.latitude && pos.coords.longitude) {
+              setLatitude(pos.coords.latitude)
+              setLongitude(pos.coords.longitude)
```
Comment (Haider8) [inline src/components/Home/Home.js:28]: Rather than separately changing latitude and then longitude. Can we make one reducer for location state?

File: src/components/Home/Home.js [hunk 3]
```diff
@@ -1,12 +1,15 @@
...
 import Header from '../Layouts/Header'
 import Shop from './Shop'
-import axios from '../../axios'
+import React, { useEffect, useReducer, useState } from 'react'
 import reducer, { initialState } from './reducer'
-import ErrorModal from '../../UI/ErrorModal'
 
 const loadingShops = Array.from(Array(8)).map(() => Math.floor(Math.random() * 1000))
+const navigatorTimeout = { timeout: 15 * 1000 }
+const localStorageExpiryMin = 10 * 60 * 1000
```
[the remark this answers is not in the document]
Comment (Haider8) [reply src/components/Home/Home.js:12]: Similary, this can also be put inside settings module

**Review by Haider8 — CHANGES_REQUESTED** [review]

**Comment by Haider8** [comment]
@ashrafmahmood Code is working fine as far as I can test. But we can make our code a little bit more readable.

**Comment by ashrafmahmood** [comment]
@Haider8 Please now check this PR

**Review by Haider8 — CHANGES_REQUESTED** [review]

File: src/const/httpStatus.js [hunk 4]
```diff
@@ -0,0 +1,4 @@
+// store the http status code
+export const HTTP_200 = 200
+export const HTTP_404 = 404
```
Comment (Haider8) [inline src/const/httpStatus.js:3]: Make it descriptive. Like HTTP_404_NOT_FOUND

Comment (Haider8) [reply src/const/httpStatus.js:3]: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

File: src/const/navigatorErrorCode.js [hunk 5]
```diff
@@ -0,0 +1,4 @@
+// store the navigator error code
+export const ERROR_CODE_1 = 1
+export const ERROR_CODE_2 = 2
+export const ERROR_CODE_3 = 3
```
Comment (Haider8) [inline src/const/navigatorErrorCode.js:4]: Make it descriptive. Like NAVIGATOR_TIMEOUT_ERROR

File: src/utils/storage.js [hunk 6]
```diff
@@ -0,0 +1,12 @@
+
+export function getLocalStorage (key) {
```
Comment (Haider8) [inline src/utils/storage.js:2]: getFromLocalStorage

**Review by Haider8 — CHANGES_REQUESTED** [review]

File: src/utils/storage.js (hunk 6 above)
Comment (ashrafmahmood) [reply src/utils/storage.js:2]: setToLocalStorage?

Comment (ashrafmahmood) [reply src/utils/storage.js:2]:
```suggestion
export function setLocalStorage (key) {
```
setToLocalStorage ?

Comment (ashrafmahmood) [reply src/utils/storage.js:2]: setToLocalStorage ?

Comment (ashrafmahmood) [reply src/utils/storage.js:2]: export const NAVIGATOR_PERMISSION_DENIED_ERROR = 1
export const NAVIGATOR_POSITION_UNAVAILABLE_ERROR = 2
export const NAVIGATOR_TIMEOUT_ERROR = 3

Is this correct now?

File: src/components/Home/Home.js [hunk 7]
```diff
@@ -32,15 +32,15 @@ function Home () {
             }
           }, (error) => {
             switch (error.code) {
-              case ERROR_CODE_1: {
+              case NAVIGATOR_PERMISSION_DENIED_ERROR: {
                 httpDispatch({ type: 'ERROR', errorMessage: 'Please allow to access your location' })
```
Comment (Haider8) [inline src/components/Home/Home.js:36]: Please allow access to your location

**Review by Haider8 — APPROVED** [review]
